"""
geodompy - Datos geoespaciales de Republica Dominicana para Python.
"""

from geodompy.cache import gd_get_dataset, get_dataset
from geodompy.clean import (
    clean_bparaje_name,
    clean_dm_name,
    clean_municipality_name,
    clean_prov_name,
    clean_region_name,
    clean_section_name,
    clean_zone_name,
    gd_clean_bparaje_name,
    gd_clean_dm_name,
    gd_clean_municipality_name,
    gd_clean_prov_name,
    gd_clean_region_name,
    gd_clean_section_name,
    gd_clean_zone_name,
)
from geodompy.data import (
    bparajes,
    dm,
    gd_bparajes,
    gd_dm,
    gd_macroregions,
    gd_municipalities,
    gd_provinces,
    gd_regions,
    gd_sections,
    gd_zones,
    macroregions,
    municipalities,
    provinces,
    regions,
    sections,
    zones,
)
from geodompy.detect import (
    analyze_columns,
    detect_column_type,
    detect_fill,
    detect_level,
    gd_analyze_columns,
    gd_detect_column_type,
    gd_detect_fill,
    gd_detect_level,
)
from geodompy.hierarchy import add_parent_cols, gd_add_parent_cols
from geodompy.map import gd_geom_sf, gd_map, gd_map_data, gd_mpl_plot, map, map_data

__version__ = "0.2.0"

__all__ = [
    "provinces",
    "regions",
    "municipalities",
    "dm",
    "sections",
    "zones",
    "bparajes",
    "macroregions",
    "get_dataset",
    "detect_level",
    "detect_fill",
    "detect_column_type",
    "analyze_columns",
    "map",
    "map_data",
    "gd_mpl_plot",
    "gd_geom_sf",
    "clean_prov_name",
    "clean_region_name",
    "clean_municipality_name",
    "clean_dm_name",
    "clean_section_name",
    "clean_bparaje_name",
    "clean_zone_name",
    "add_parent_cols",
    "gd_provinces",
    "gd_regions",
    "gd_municipalities",
    "gd_dm",
    "gd_sections",
    "gd_zones",
    "gd_bparajes",
    "gd_macroregions",
    "gd_get_dataset",
    "gd_detect_level",
    "gd_detect_fill",
    "gd_detect_column_type",
    "gd_analyze_columns",
    "gd_map",
    "gd_map_data",
    "gd_clean_prov_name",
    "gd_clean_region_name",
    "gd_clean_municipality_name",
    "gd_clean_dm_name",
    "gd_clean_section_name",
    "gd_clean_bparaje_name",
    "gd_clean_zone_name",
    "gd_add_parent_cols",
]
